### ISSUE TITLE
játékos mozgása (alap)

### ISSUE THREAD

**Issue by nomansnick** [flowacademyhu/die-by-the-box#3]
az almas alapján nézd át a játékost pls. itt csak két irányba fog mozogni, ha van akadaly if-fel megmásthatja.

ezzel sztem holnap haladunk, mert ezt is át kéne beszélni sztem, de ahogy érzed

**Comment by danielvarsas** [comment]
Majd mutassa meg valaki légyszi, hogy kell visszavonni feltöltést. (Felnyomtam egy index.js-t egy másik mappából véletlen.)
